// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateTaskRequest {
    /**
     * Creates a new CreateTaskRequest instance.
     * @param {Partial<CreateTaskRequest>} [$$source = {}] - The source object to create the CreateTaskRequest.
     */
    constructor($$source = {}) {
        if (!("bizType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bizType"] = "";
        }
        if (!("bizId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bizId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("enId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["enId"] = "";
        }
        if (!("articleId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["articleId"] = 0;
        }
        if (!("downloadType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloadType"] = 0;
        }
        if (!("saveDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveDir"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("payloadJson" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["payloadJson"] = "";
        }
        if (!("maxRetries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRetries"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTaskRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTaskRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTaskRequest(/** @type {Partial<CreateTaskRequest>} */($$parsedSource));
    }
}

export class DownloadTask {
    /**
     * Creates a new DownloadTask instance.
     * @param {Partial<DownloadTask>} [$$source = {}] - The source object to create the DownloadTask.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("bizType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bizType"] = "";
        }
        if (!("bizId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bizId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("enId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["enId"] = "";
        }
        if (!("articleId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["articleId"] = 0;
        }
        if (!("downloadType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloadType"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("currentName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentName"] = "";
        }
        if (!("saveDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveDir"] = "";
        }
        if (!("payloadJson" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["payloadJson"] = "";
        }
        if (!("retryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retryCount"] = 0;
        }
        if (!("maxRetries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRetries"] = 0;
        }
        if (!("nextRetryAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["nextRetryAt"] = null;
        }
        if (!("errorCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorCode"] = "";
        }
        if (!("errorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorMessage"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["startedAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["finishedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadTask}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadTask(/** @type {Partial<DownloadTask>} */($$parsedSource));
    }
}

export class ListTaskQuery {
    /**
     * Creates a new ListTaskQuery instance.
     * @param {Partial<ListTaskQuery>} [$$source = {}] - The source object to create the ListTaskQuery.
     */
    constructor($$source = {}) {
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["status"] = [];
        }
        if (!("bizType" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["bizType"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListTaskQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListTaskQuery}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField2_0($$parsedSource["status"]);
        }
        if ("bizType" in $$parsedSource) {
            $$parsedSource["bizType"] = $$createField3_0($$parsedSource["bizType"]);
        }
        return new ListTaskQuery(/** @type {Partial<ListTaskQuery>} */($$parsedSource));
    }
}

export class ListTaskResult {
    /**
     * Creates a new ListTaskResult instance.
     * @param {Partial<ListTaskResult>} [$$source = {}] - The source object to create the ListTaskResult.
     */
    constructor($$source = {}) {
        if (!("list" in $$source)) {
            /**
             * @member
             * @type {DownloadTask[]}
             */
            this["list"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListTaskResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListTaskResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField0_0($$parsedSource["list"]);
        }
        return new ListTaskResult(/** @type {Partial<ListTaskResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DownloadTask.createFrom;
const $$createType2 = $Create.Array($$createType1);
