// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {backend} from '../models';

export function ArticleDetail(arg1:number,arg2:string):Promise<string>;

export function ArticleList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<services.ArticleList>;

export function CheckLogin(arg1:string,arg2:string):Promise<backend.LoginResult>;

export function CourseCategory():Promise<Array<services.CourseCategory>>;

export function CourseDownload(arg1:number,arg2:number,arg3:number):Promise<void>;

export function CourseInfo(arg1:string):Promise<services.CourseInfo>;

export function CourseList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<services.CourseList>;

export function EbookCommentList(arg1:string,arg2:number,arg3:number):Promise<services.EbookCommentList>;

export function EbookDownload(arg1:number,arg2:number):Promise<void>;

export function EbookInfo(arg1:string):Promise<services.EbookDetail>;

export function EbookUserInfo():Promise<services.EbookVIPInfo>;

export function GetQrcode():Promise<backend.QrCodeResp>;

export function GetVolcPlayAuthToken(arg1:string,arg2:string):Promise<services.MediaVolc>;

export function GetVolcPlayInfo(arg1:string):Promise<services.VodPlayInfoResp>;

export function OdobDownload(arg1:number,arg2:number):Promise<void>;

export function OdobUserInfo():Promise<services.OdobVip>;

export function UserInfo():Promise<services.User>;
