// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {backend} from '../models';

export function AlgoFilter(arg1:services.AlgoFilterParam):Promise<any>;

export function AlgoProduct(arg1:services.AlgoFilterParam):Promise<any>;

export function ArticleDetail(arg1:number,arg2:string):Promise<string>;

export function ArticleList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<any>;

export function CheckLogin(arg1:string,arg2:string):Promise<backend.LoginResult>;

export function CourseCategory():Promise<Array<services.CourseCategory>>;

export function CourseDownload(arg1:number,arg2:number,arg3:number,arg4:string):Promise<void>;

export function CourseInfo(arg1:string):Promise<any>;

export function CourseList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<any>;

export function EbookCommentList(arg1:string,arg2:number,arg3:number):Promise<any>;

export function EbookDownload(arg1:number,arg2:number,arg3:string):Promise<void>;

export function EbookInfo(arg1:string):Promise<any>;

export function EbookShelfAdd(arg1:Array<string>):Promise<any>;

export function EbookUserInfo():Promise<any>;

export function GetHomeInitialState():Promise<services.HomeInitState>;

export function GetQrcode():Promise<backend.QrCodeResp>;

export function GetVolcPlayAuthToken(arg1:string,arg2:string):Promise<any>;

export function GetVolcPlayInfo(arg1:string):Promise<any>;

export function Logout():Promise<void>;

export function NotesTimeline(arg1:string):Promise<any>;

export function OdobDownload(arg1:number,arg2:number,arg3:any):Promise<void>;

export function OdobUserInfo():Promise<any>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function SearchHot():Promise<any>;

export function SetDir(arg1:Array<string>):Promise<void>;

export function SunflowerLabelContent(arg1:string,arg2:number,arg3:number,arg4:number):Promise<any>;

export function SunflowerLabelList(arg1:number):Promise<any>;

export function SunflowerResourceList():Promise<any>;

export function TopicAll(arg1:number,arg2:number):Promise<any>;

export function TopicNoteDetail(arg1:string):Promise<any>;

export function TopicNotesList(arg1:string,arg2:boolean,arg3:number,arg4:number):Promise<any>;

export function UserInfo():Promise<any>;
