// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloadmgr$0 from "./downloadmgr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {services$0.AlgoFilterParam} param
 * @returns {$CancellablePromise<services$0.AlgoFilterResp | null>}
 */
export function AlgoFilter(param) {
    return $Call.ByID(680027832, param).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {services$0.AlgoFilterParam} param
 * @returns {$CancellablePromise<services$0.AlgoProductResp | null>}
 */
export function AlgoProduct(param) {
    return $Call.ByID(2697748981, param).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ArticleDetail
 * enid article enid  or odob audioAliasID, aType 1-course article, 2-odob article
 * @param {number} aType
 * @param {string} aEnid
 * @returns {$CancellablePromise<string>}
 */
export function ArticleDetail(aType, aEnid) {
    return $Call.ByID(1803400456, aType, aEnid);
}

/**
 * @param {string} enid
 * @param {string} chapterID
 * @param {number} count
 * @param {number} maxID
 * @param {boolean} reverse
 * @returns {$CancellablePromise<services$0.ArticleList | null>}
 */
export function ArticleList(enid, chapterID, count, maxID, reverse) {
    return $Call.ByID(1411892165, enid, chapterID, count, maxID, reverse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * AudioDetail 听书简介
 * @param {string} id
 * @returns {$CancellablePromise<services$0.AudioInfoResp | null>}
 */
export function AudioDetail(id) {
    return $Call.ByID(1471307848, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * AudioDetailAlias 听书音频播放信息（包含 mp3_play_url）
 * @param {string} aliasID
 * @returns {$CancellablePromise<services$0.Audio | null>}
 */
export function AudioDetailAlias(aliasID) {
    return $Call.ByID(1952664356, aliasID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CancelDownloadTask(id) {
    return $Call.ByID(3740896326, id);
}

/**
 * ChannelHomepage 获取学习圈频道首页分类
 * @param {number} channelID
 * @returns {$CancellablePromise<services$0.ChannelHomepageCategory[]>}
 */
export function ChannelHomepage(channelID) {
    return $Call.ByID(3877179928, channelID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ChannelInfo 获取学习圈频道信息
 * @param {number} channelID
 * @returns {$CancellablePromise<services$0.ChannelInfo | null>}
 */
export function ChannelInfo(channelID) {
    return $Call.ByID(2123932888, channelID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * ChannelTopicDetail 根据主题ID获取主题详情列表
 * @param {number} productID
 * @returns {$CancellablePromise<services$0.ChannelTopicCategory | null>}
 */
export function ChannelTopicDetail(productID) {
    return $Call.ByID(2133429882, productID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ChannelVipInfo 获取学习圈VIP/权限信息
 * @param {number} channelID
 * @returns {$CancellablePromise<services$0.ChannelVipInfo | null>}
 */
export function ChannelVipInfo(channelID) {
    return $Call.ByID(103430851, channelID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} token
 * @param {string} qrCodeString
 * @returns {$CancellablePromise<$models.LoginResult>}
 */
export function CheckLogin(token, qrCodeString) {
    return $Call.ByID(584540236, token, qrCodeString).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {boolean} clearAll
 * @returns {$CancellablePromise<void>}
 */
export function ClearDownloadTasks(clearAll) {
    return $Call.ByID(3974428356, clearAll);
}

/**
 * @returns {$CancellablePromise<services$0.CourseCategory[]>}
 */
export function CourseCategory() {
    return $Call.ByID(146620176).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {number} id
 * @param {number} aid
 * @param {number} dType
 * @param {string} enid
 * @returns {$CancellablePromise<void>}
 */
export function CourseDownload(id, aid, dType, enid) {
    return $Call.ByID(4237804328, id, aid, dType, enid);
}

/**
 * @param {string} category
 * @param {string} order
 * @param {string} filter
 * @param {number} groupID
 * @param {number} page
 * @param {number} limit
 * @returns {$CancellablePromise<services$0.CourseList | null>}
 */
export function CourseGroupList(category, order, filter, groupID, page, limit) {
    return $Call.ByID(906959299, category, order, filter, groupID, page, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {string} enid
 * @returns {$CancellablePromise<services$0.CourseInfo | null>}
 */
export function CourseInfo(enid) {
    return $Call.ByID(2389583268, enid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} category
 * @param {string} order
 * @param {string} filter
 * @param {number} page
 * @param {number} limit
 * @returns {$CancellablePromise<services$0.CourseList | null>}
 */
export function CourseList(category, order, filter, page, limit) {
    return $Call.ByID(1314931904, category, order, filter, page, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {downloadmgr$0.CreateTaskRequest} req
 * @returns {$CancellablePromise<downloadmgr$0.DownloadTask | null>}
 */
export function CreateDownloadTask(req) {
    return $Call.ByID(2456452320, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @param {string} enid
 * @param {number} page
 * @param {number} limit
 * @returns {$CancellablePromise<services$0.EbookCommentList | null>}
 */
export function EbookCommentList(enid, page, limit) {
    return $Call.ByID(2201437706, enid, page, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {number} id
 * @param {number} dType
 * @param {string} enid
 * @returns {$CancellablePromise<void>}
 */
export function EbookDownload(id, dType, enid) {
    return $Call.ByID(1613439865, id, dType, enid);
}

/**
 * @param {string} enid
 * @returns {$CancellablePromise<services$0.EbookDetail | null>}
 */
export function EbookInfo(enid) {
    return $Call.ByID(2688974469, enid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {string[]} enids
 * @returns {$CancellablePromise<services$0.EbookShelfAddResp | null>}
 */
export function EbookShelfAdd(enids) {
    return $Call.ByID(3228090406, enids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @param {string[]} enids
 * @returns {$CancellablePromise<services$0.EbookShelfAddResp | null>}
 */
export function EbookShelfRemove(enids) {
    return $Call.ByID(1745956559, enids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.EbookVIPInfo | null>}
 */
export function EbookUserInfo() {
    return $Call.ByID(3935865418).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @param {number} aType
 * @param {string} enid
 * @returns {$CancellablePromise<services$0.ArticleIntro | null>}
 */
export function GetArticleIntro(aType, enid) {
    return $Call.ByID(2072773507, aType, enid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<downloadmgr$0.DownloadTask | null>}
 */
export function GetDownloadTask(id) {
    return $Call.ByID(3402241922, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.HomeInitState>}
 */
export function GetHomeInitialState() {
    return $Call.ByID(1676303509).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.NavbarData | null>}
 */
export function GetNavbar() {
    return $Call.ByID(106386349).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.QrCodeResp>}
 */
export function GetQrcode() {
    return $Call.ByID(1218946645).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * @param {string} mediaID
 * @param {string} securityToken
 * @returns {$CancellablePromise<services$0.MediaVolc | null>}
 */
export function GetVolcPlayAuthToken(mediaID, securityToken) {
    return $Call.ByID(4228533254, mediaID, securityToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<services$0.VodPlayInfoResp | null>}
 */
export function GetVolcPlayInfo(query) {
    return $Call.ByID(714407619, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * @param {downloadmgr$0.ListTaskQuery} query
 * @returns {$CancellablePromise<downloadmgr$0.ListTaskResult>}
 */
export function ListDownloadTasks(query) {
    return $Call.ByID(1356144309, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(244089579);
}

/**
 * NotesTimeline 知识城邦首页时间线列表
 * @param {string} maxID
 * @returns {$CancellablePromise<services$0.NotesTimeline | null>}
 */
export function NotesTimeline(maxID) {
    return $Call.ByID(1512365889, maxID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * @param {number} id
 * @param {number} dType
 * @param {services$0.Course | null} data
 * @returns {$CancellablePromise<void>}
 */
export function OdobDownload(id, dType, data) {
    return $Call.ByID(1556938807, id, dType, data);
}

/**
 * @param {string[]} enids
 * @returns {$CancellablePromise<services$0.EbookShelfAddResp | null>}
 */
export function OdobShelfAdd(enids) {
    return $Call.ByID(257760724, enids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.OdobVip | null>}
 */
export function OdobUserInfo() {
    return $Call.ByID(577705820).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * @param {application$0.SecondInstanceData} secondInstanceData
 * @returns {$CancellablePromise<void>}
 */
export function OnSecondInstanceLaunch(secondInstanceData) {
    return $Call.ByID(3855456648, secondInstanceData);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog(title) {
    return $Call.ByID(3767452308, title);
}

/**
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(title) {
    return $Call.ByID(832231451, title);
}

/**
 * @param {string} enid
 * @returns {$CancellablePromise<services$0.OutsideDetail | null>}
 */
export function OutsideDetail(enid) {
    return $Call.ByID(1787399093, enid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function PauseDownloadTask(id) {
    return $Call.ByID(2527885872, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ResumeDownloadTask(id) {
    return $Call.ByID(3740811607, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RetryDownloadTask(id) {
    return $Call.ByID(3741137836, id);
}

/**
 * @returns {$CancellablePromise<services$0.SearchTot | null>}
 */
export function SearchHot() {
    return $Call.ByID(910533088).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * @param {string[]} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetDir(dir) {
    return $Call.ByID(1215717506, dir);
}

/**
 * @param {string} enID
 * @param {number} nType
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<services$0.SunflowerContent | null>}
 */
export function SunflowerLabelContent(enID, nType, page, pageSize) {
    return $Call.ByID(4257134821, enID, nType, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * SunflowerLabelList 首页导航标签列表
 * 2-好看又好查的电子书, 4-精选课程
 * @param {number} nType
 * @returns {$CancellablePromise<services$0.SunflowerLabelList | null>}
 */
export function SunflowerLabelList(nType) {
    return $Call.ByID(835478792, nType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.SunflowerResourceList | null>}
 */
export function SunflowerResourceList() {
    return $Call.ByID(604570190).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * TopicAll 推荐话题列表
 * @param {number} page
 * @param {number} limit
 * @returns {$CancellablePromise<services$0.TopicAll | null>}
 */
export function TopicAll(page, limit) {
    return $Call.ByID(1402317375, page, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * TopicNoteDetail 话题笔记详情
 * @param {string} id
 * @returns {$CancellablePromise<services$0.TopicDetail | null>}
 */
export function TopicNoteDetail(id) {
    return $Call.ByID(3403994225, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * TopicNotesList 话题笔记列表
 * isElected true 精选，false 最新
 * @param {string} id
 * @param {boolean} isElected
 * @param {number} page
 * @param {number} limit
 * @returns {$CancellablePromise<services$0.NotesList | null>}
 */
export function TopicNotesList(id, isElected, page, limit) {
    return $Call.ByID(1175143493, id, isElected, page, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * @returns {$CancellablePromise<services$0.User | null>}
 */
export function UserInfo() {
    return $Call.ByID(1139105482).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType67($result);
    }));
}

// Private type creation functions
const $$createType0 = services$0.AlgoFilterResp.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = services$0.AlgoProductResp.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = services$0.ArticleList.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = services$0.AudioInfoResp.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = services$0.Audio.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = services$0.ChannelHomepageCategory.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = services$0.ChannelInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = services$0.ChannelTopicCategory.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = services$0.ChannelVipInfo.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.LoginResult.createFrom;
const $$createType19 = services$0.CourseCategory.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = services$0.CourseList.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = services$0.CourseInfo.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = downloadmgr$0.DownloadTask.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = services$0.EbookCommentList.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = services$0.EbookDetail.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = services$0.EbookShelfAddResp.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = services$0.EbookVIPInfo.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = services$0.ArticleIntro.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = services$0.HomeInitState.createFrom;
const $$createType38 = services$0.NavbarData.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $models.QrCodeResp.createFrom;
const $$createType41 = services$0.MediaVolc.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = services$0.VodPlayInfoResp.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = downloadmgr$0.ListTaskResult.createFrom;
const $$createType46 = services$0.NotesTimeline.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = services$0.OdobVip.createFrom;
const $$createType49 = $Create.Nullable($$createType48);
const $$createType50 = services$0.OutsideDetail.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = services$0.SearchTot.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = services$0.SunflowerContent.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = services$0.SunflowerLabelList.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = services$0.SunflowerResourceList.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = services$0.TopicAll.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = services$0.TopicDetail.createFrom;
const $$createType63 = $Create.Nullable($$createType62);
const $$createType64 = services$0.NotesList.createFrom;
const $$createType65 = $Create.Nullable($$createType64);
const $$createType66 = services$0.User.createFrom;
const $$createType67 = $Create.Nullable($$createType66);
