// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

export class LoginResult {
    /**
     * Creates a new LoginResult instance.
     * @param {Partial<LoginResult>} [$$source = {}] - The source object to create the LoginResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * 1-登录成功,2-二维码过期
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("cookie" in $$source)) {
            /**
             * cookies string
             * @member
             * @type {string}
             */
            this["cookie"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {services$0.User | null}
             */
            this["user"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField2_0($$parsedSource["user"]);
        }
        return new LoginResult(/** @type {Partial<LoginResult>} */($$parsedSource));
    }
}

export class QrCodeResp {
    /**
     * Creates a new QrCodeResp instance.
     * @param {Partial<QrCodeResp>} [$$source = {}] - The source object to create the QrCodeResp.
     */
    constructor($$source = {}) {
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("qrCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qrCode"] = "";
        }
        if (!("qrCodeString" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qrCodeString"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QrCodeResp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QrCodeResp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QrCodeResp(/** @type {Partial<QrCodeResp>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = services$0.User.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
