// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SecondInstanceData contains information about the second instance launch
 */
export class SecondInstanceData {
    /**
     * Creates a new SecondInstanceData instance.
     * @param {Partial<SecondInstanceData>} [$$source = {}] - The source object to create the SecondInstanceData.
     */
    constructor($$source = {}) {
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["args"] = [];
        }
        if (!("workingDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workingDir"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["additionalData"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecondInstanceData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SecondInstanceData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField0_0($$parsedSource["args"]);
        }
        if ("additionalData" in $$parsedSource) {
            $$parsedSource["additionalData"] = $$createField2_0($$parsedSource["additionalData"]);
        }
        return new SecondInstanceData(/** @type {Partial<SecondInstanceData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
